# Estágio 1: Build da aplicação com Maven
FROM maven:3.9.6-eclipse-temurin-21 AS build
WORKDIR /app
COPY pom.xml .
COPY src ./src
RUN mvn clean package -DskipTests

# Estágio 2: Execução com JRE leve e otimização de memória
FROM eclipse-temurin:21-jre-alpine
WORKDIR /app
COPY --from=build /app/target/*.jar app.jar

# Limitação estrita de memória para rodar liso no plano gratuito
ENV JAVA_OPTS="-Xmx256m -Xms128m"

# Define uma porta padrão caso rode local, mas o Render vai sobrescrever isso
ENV PORT=8080
EXPOSE $PORT

# forçamos o Spring a ler a variável $PORT do Render
ENTRYPOINT ["sh", "-c", "java $JAVA_OPTS -Dserver.port=$PORT -jar app.jar"]